version: "3.9"
services:
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: ithunjanthanne
      POSTGRES_DB: e_commerce
    ports:
      - "5432:5433"  # Expose PostgreSQL port
    volumes:
      - db-data:/var/lib/postgresql/data

  web:
    image: ecommerce:latest
    ports:
      - "8080:8080"
    environment:
      DB_HOST: postgres  
      DB_PORT: 5433  # Corrected to match the exposed port of the db service
      DB_NAME: e_commerce
      DB_USER: postgres
      DB_PASSWORD: ithunjanthanne
    depends_on:
      - db
    volumes:
      - ./template:/app/template

volumes:
  db-data:
