// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	helperstructs "ecommerce/web/helpers/helper_structs"

	mock "github.com/stretchr/testify/mock"

	responce "ecommerce/web/helpers/responce"
)

// AdminRepo is an autogenerated mock type for the AdminRepo type
type AdminRepo struct {
	mock.Mock
}

// GetAllUsers provides a mock function with given fields:
func (_m *AdminRepo) GetAllUsers() ([]responce.AdminsideUsersData, error) {
	ret := _m.Called()

	var r0 []responce.AdminsideUsersData
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]responce.AdminsideUsersData, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []responce.AdminsideUsersData); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]responce.AdminsideUsersData)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByEmail provides a mock function with given fields: admin
func (_m *AdminRepo) GetByEmail(admin helperstructs.AdminReq) (responce.AdminData, error) {
	ret := _m.Called(admin)

	var r0 responce.AdminData
	var r1 error
	if rf, ok := ret.Get(0).(func(helperstructs.AdminReq) (responce.AdminData, error)); ok {
		return rf(admin)
	}
	if rf, ok := ret.Get(0).(func(helperstructs.AdminReq) responce.AdminData); ok {
		r0 = rf(admin)
	} else {
		r0 = ret.Get(0).(responce.AdminData)
	}

	if rf, ok := ret.Get(1).(func(helperstructs.AdminReq) error); ok {
		r1 = rf(admin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReports provides a mock function with given fields: email
func (_m *AdminRepo) GetReports(email string) (int, error) {
	ret := _m.Called(email)

	var r0 int
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (int, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) int); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(int)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetUser provides a mock function with given fields: email
func (_m *AdminRepo) GetUser(email string) (responce.AdminsideUsersData, error) {
	ret := _m.Called(email)

	var r0 responce.AdminsideUsersData
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (responce.AdminsideUsersData, error)); ok {
		return rf(email)
	}
	if rf, ok := ret.Get(0).(func(string) responce.AdminsideUsersData); ok {
		r0 = rf(email)
	} else {
		r0 = ret.Get(0).(responce.AdminsideUsersData)
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// ReportUser provides a mock function with given fields: reportreq
func (_m *AdminRepo) ReportUser(reportreq helperstructs.ReportReq) error {
	ret := _m.Called(reportreq)

	var r0 error
	if rf, ok := ret.Get(0).(func(helperstructs.ReportReq) error); ok {
		r0 = rf(reportreq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewAdminRepo creates a new instance of AdminRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewAdminRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *AdminRepo {
	mock := &AdminRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
