// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	helperstructs "ecommerce/web/helpers/helper_structs"

	mock "github.com/stretchr/testify/mock"

	responce "ecommerce/web/helpers/responce"
)

// BrandRepo is an autogenerated mock type for the BrandRepo type
type BrandRepo struct {
	mock.Mock
}

// CreateBrand provides a mock function with given fields: brandreq
func (_m *BrandRepo) CreateBrand(brandreq helperstructs.BrandReq) (responce.BrandData, error) {
	ret := _m.Called(brandreq)

	var r0 responce.BrandData
	var r1 error
	if rf, ok := ret.Get(0).(func(helperstructs.BrandReq) (responce.BrandData, error)); ok {
		return rf(brandreq)
	}
	if rf, ok := ret.Get(0).(func(helperstructs.BrandReq) responce.BrandData); ok {
		r0 = rf(brandreq)
	} else {
		r0 = ret.Get(0).(responce.BrandData)
	}

	if rf, ok := ret.Get(1).(func(helperstructs.BrandReq) error); ok {
		r1 = rf(brandreq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteBrand provides a mock function with given fields: brand_id
func (_m *BrandRepo) DeleteBrand(brand_id uint) error {
	ret := _m.Called(brand_id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(brand_id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetallBrand provides a mock function with given fields:
func (_m *BrandRepo) GetallBrand() ([]responce.BrandData, error) {
	ret := _m.Called()

	var r0 []responce.BrandData
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]responce.BrandData, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []responce.BrandData); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]responce.BrandData)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateBrand provides a mock function with given fields: brandreq
func (_m *BrandRepo) UpdateBrand(brandreq helperstructs.BrandReq) (responce.BrandData, error) {
	ret := _m.Called(brandreq)

	var r0 responce.BrandData
	var r1 error
	if rf, ok := ret.Get(0).(func(helperstructs.BrandReq) (responce.BrandData, error)); ok {
		return rf(brandreq)
	}
	if rf, ok := ret.Get(0).(func(helperstructs.BrandReq) responce.BrandData); ok {
		r0 = rf(brandreq)
	} else {
		r0 = ret.Get(0).(responce.BrandData)
	}

	if rf, ok := ret.Get(1).(func(helperstructs.BrandReq) error); ok {
		r1 = rf(brandreq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewBrandRepo creates a new instance of BrandRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewBrandRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *BrandRepo {
	mock := &BrandRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
