// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"
	helperstructs "ecommerce/web/helpers/helper_structs"

	mock "github.com/stretchr/testify/mock"

	responce "ecommerce/web/helpers/responce"
)

// CategoryUsecaseInterface is an autogenerated mock type for the CategoryUsecaseInterface type
type CategoryUsecaseInterface struct {
	mock.Mock
}

// CreateCategory provides a mock function with given fields: ctx, catreq
func (_m *CategoryUsecaseInterface) CreateCategory(ctx context.Context, catreq helperstructs.CategoryReq) (responce.CategoryData, error) {
	ret := _m.Called(ctx, catreq)

	var r0 responce.CategoryData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, helperstructs.CategoryReq) (responce.CategoryData, error)); ok {
		return rf(ctx, catreq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, helperstructs.CategoryReq) responce.CategoryData); ok {
		r0 = rf(ctx, catreq)
	} else {
		r0 = ret.Get(0).(responce.CategoryData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, helperstructs.CategoryReq) error); ok {
		r1 = rf(ctx, catreq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteCategory provides a mock function with given fields: ctx, cat_id
func (_m *CategoryUsecaseInterface) DeleteCategory(ctx context.Context, cat_id uint) error {
	ret := _m.Called(ctx, cat_id)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, uint) error); ok {
		r0 = rf(ctx, cat_id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllCategories provides a mock function with given fields: ctx
func (_m *CategoryUsecaseInterface) GetAllCategories(ctx context.Context) ([]responce.CategoryData, error) {
	ret := _m.Called(ctx)

	var r0 []responce.CategoryData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]responce.CategoryData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []responce.CategoryData); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]responce.CategoryData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateCategory provides a mock function with given fields: ctx, catreq
func (_m *CategoryUsecaseInterface) UpdateCategory(ctx context.Context, catreq helperstructs.CategoryReq) (responce.CategoryData, error) {
	ret := _m.Called(ctx, catreq)

	var r0 responce.CategoryData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, helperstructs.CategoryReq) (responce.CategoryData, error)); ok {
		return rf(ctx, catreq)
	}
	if rf, ok := ret.Get(0).(func(context.Context, helperstructs.CategoryReq) responce.CategoryData); ok {
		r0 = rf(ctx, catreq)
	} else {
		r0 = ret.Get(0).(responce.CategoryData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, helperstructs.CategoryReq) error); ok {
		r1 = rf(ctx, catreq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewCategoryUsecaseInterface creates a new instance of CategoryUsecaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewCategoryUsecaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *CategoryUsecaseInterface {
	mock := &CategoryUsecaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
