// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	helperstructs "ecommerce/web/helpers/helper_structs"

	mock "github.com/stretchr/testify/mock"

	responce "ecommerce/web/helpers/responce"
)

// DiscountRepo is an autogenerated mock type for the DiscountRepo type
type DiscountRepo struct {
	mock.Mock
}

// AddDiscount provides a mock function with given fields: discountreq
func (_m *DiscountRepo) AddDiscount(discountreq helperstructs.DiscountReq) (responce.DiscountData, error) {
	ret := _m.Called(discountreq)

	var r0 responce.DiscountData
	var r1 error
	if rf, ok := ret.Get(0).(func(helperstructs.DiscountReq) (responce.DiscountData, error)); ok {
		return rf(discountreq)
	}
	if rf, ok := ret.Get(0).(func(helperstructs.DiscountReq) responce.DiscountData); ok {
		r0 = rf(discountreq)
	} else {
		r0 = ret.Get(0).(responce.DiscountData)
	}

	if rf, ok := ret.Get(1).(func(helperstructs.DiscountReq) error); ok {
		r1 = rf(discountreq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// DeleteDiscount provides a mock function with given fields: id
func (_m *DiscountRepo) DeleteDiscount(id uint) error {
	ret := _m.Called(id)

	var r0 error
	if rf, ok := ret.Get(0).(func(uint) error); ok {
		r0 = rf(id)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// GetAllDiscounts provides a mock function with given fields:
func (_m *DiscountRepo) GetAllDiscounts() ([]responce.DiscountData, error) {
	ret := _m.Called()

	var r0 []responce.DiscountData
	var r1 error
	if rf, ok := ret.Get(0).(func() ([]responce.DiscountData, error)); ok {
		return rf()
	}
	if rf, ok := ret.Get(0).(func() []responce.DiscountData); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]responce.DiscountData)
		}
	}

	if rf, ok := ret.Get(1).(func() error); ok {
		r1 = rf()
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetByID provides a mock function with given fields: category_id
func (_m *DiscountRepo) GetByID(category_id uint) (responce.DiscountData, error) {
	ret := _m.Called(category_id)

	var r0 responce.DiscountData
	var r1 error
	if rf, ok := ret.Get(0).(func(uint) (responce.DiscountData, error)); ok {
		return rf(category_id)
	}
	if rf, ok := ret.Get(0).(func(uint) responce.DiscountData); ok {
		r0 = rf(category_id)
	} else {
		r0 = ret.Get(0).(responce.DiscountData)
	}

	if rf, ok := ret.Get(1).(func(uint) error); ok {
		r1 = rf(category_id)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UpdateDiscount provides a mock function with given fields: discountreq
func (_m *DiscountRepo) UpdateDiscount(discountreq helperstructs.DiscountReq) (responce.DiscountData, error) {
	ret := _m.Called(discountreq)

	var r0 responce.DiscountData
	var r1 error
	if rf, ok := ret.Get(0).(func(helperstructs.DiscountReq) (responce.DiscountData, error)); ok {
		return rf(discountreq)
	}
	if rf, ok := ret.Get(0).(func(helperstructs.DiscountReq) responce.DiscountData); ok {
		r0 = rf(discountreq)
	} else {
		r0 = ret.Get(0).(responce.DiscountData)
	}

	if rf, ok := ret.Get(1).(func(helperstructs.DiscountReq) error); ok {
		r1 = rf(discountreq)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewDiscountRepo creates a new instance of DiscountRepo. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewDiscountRepo(t interface {
	mock.TestingT
	Cleanup(func())
}) *DiscountRepo {
	mock := &DiscountRepo{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
