// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"
	helperstructs "ecommerce/web/helpers/helper_structs"

	mock "github.com/stretchr/testify/mock"

	responce "ecommerce/web/helpers/responce"
)

// SuAdminUsecaseInterface is an autogenerated mock type for the SuAdminUsecaseInterface type
type SuAdminUsecaseInterface struct {
	mock.Mock
}

// BlockUser provides a mock function with given fields: ctx, blockreq
func (_m *SuAdminUsecaseInterface) BlockUser(ctx context.Context, blockreq helperstructs.BlockReq) error {
	ret := _m.Called(ctx, blockreq)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, helperstructs.BlockReq) error); ok {
		r0 = rf(ctx, blockreq)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// CreateAdmin provides a mock function with given fields: ctx, admin
func (_m *SuAdminUsecaseInterface) CreateAdmin(ctx context.Context, admin helperstructs.AdminReq) (responce.AdminData, error) {
	ret := _m.Called(ctx, admin)

	var r0 responce.AdminData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, helperstructs.AdminReq) (responce.AdminData, error)); ok {
		return rf(ctx, admin)
	}
	if rf, ok := ret.Get(0).(func(context.Context, helperstructs.AdminReq) responce.AdminData); ok {
		r0 = rf(ctx, admin)
	} else {
		r0 = ret.Get(0).(responce.AdminData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, helperstructs.AdminReq) error); ok {
		r1 = rf(ctx, admin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllAdmins provides a mock function with given fields: ctx
func (_m *SuAdminUsecaseInterface) GetAllAdmins(ctx context.Context) ([]responce.AdminData, error) {
	ret := _m.Called(ctx)

	var r0 []responce.AdminData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]responce.AdminData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []responce.AdminData); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]responce.AdminData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetAllUsers provides a mock function with given fields: ctx
func (_m *SuAdminUsecaseInterface) GetAllUsers(ctx context.Context) ([]responce.AdminsideUsersData, error) {
	ret := _m.Called(ctx)

	var r0 []responce.AdminsideUsersData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]responce.AdminsideUsersData, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []responce.AdminsideUsersData); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]responce.AdminsideUsersData)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetDetailedReport provides a mock function with given fields: ctx, email
func (_m *SuAdminUsecaseInterface) GetDetailedReport(ctx context.Context, email string) (responce.DetailReportResponce, error) {
	ret := _m.Called(ctx, email)

	var r0 responce.DetailReportResponce
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, string) (responce.DetailReportResponce, error)); ok {
		return rf(ctx, email)
	}
	if rf, ok := ret.Get(0).(func(context.Context, string) responce.DetailReportResponce); ok {
		r0 = rf(ctx, email)
	} else {
		r0 = ret.Get(0).(responce.DetailReportResponce)
	}

	if rf, ok := ret.Get(1).(func(context.Context, string) error); ok {
		r1 = rf(ctx, email)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// GetReportes provides a mock function with given fields: ctx
func (_m *SuAdminUsecaseInterface) GetReportes(ctx context.Context) ([]responce.DetailReportResponce, error) {
	ret := _m.Called(ctx)

	var r0 []responce.DetailReportResponce
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context) ([]responce.DetailReportResponce, error)); ok {
		return rf(ctx)
	}
	if rf, ok := ret.Get(0).(func(context.Context) []responce.DetailReportResponce); ok {
		r0 = rf(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]responce.DetailReportResponce)
		}
	}

	if rf, ok := ret.Get(1).(func(context.Context) error); ok {
		r1 = rf(ctx)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// SuAdminLogin provides a mock function with given fields: ctx, suadmin
func (_m *SuAdminUsecaseInterface) SuAdminLogin(ctx context.Context, suadmin helperstructs.SuAdminReq) (responce.SuAdminData, error) {
	ret := _m.Called(ctx, suadmin)

	var r0 responce.SuAdminData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, helperstructs.SuAdminReq) (responce.SuAdminData, error)); ok {
		return rf(ctx, suadmin)
	}
	if rf, ok := ret.Get(0).(func(context.Context, helperstructs.SuAdminReq) responce.SuAdminData); ok {
		r0 = rf(ctx, suadmin)
	} else {
		r0 = ret.Get(0).(responce.SuAdminData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, helperstructs.SuAdminReq) error); ok {
		r1 = rf(ctx, suadmin)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewSuAdminUsecaseInterface creates a new instance of SuAdminUsecaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewSuAdminUsecaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *SuAdminUsecaseInterface {
	mock := &SuAdminUsecaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
