// Code generated by mockery v2.36.0. DO NOT EDIT.

package mocks

import (
	context "context"
	helperstructs "ecommerce/web/helpers/helper_structs"

	mock "github.com/stretchr/testify/mock"

	responce "ecommerce/web/helpers/responce"
)

// UserUsecaseInterface is an autogenerated mock type for the UserUsecaseInterface type
type UserUsecaseInterface struct {
	mock.Mock
}

// UserLogin provides a mock function with given fields: ctx, user
func (_m *UserUsecaseInterface) UserLogin(ctx context.Context, user helperstructs.UserReq) (responce.UserData, error) {
	ret := _m.Called(ctx, user)

	var r0 responce.UserData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, helperstructs.UserReq) (responce.UserData, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, helperstructs.UserReq) responce.UserData); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(responce.UserData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, helperstructs.UserReq) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// UserSignUp provides a mock function with given fields: ctx, user
func (_m *UserUsecaseInterface) UserSignUp(ctx context.Context, user helperstructs.UserReq) (responce.UserData, error) {
	ret := _m.Called(ctx, user)

	var r0 responce.UserData
	var r1 error
	if rf, ok := ret.Get(0).(func(context.Context, helperstructs.UserReq) (responce.UserData, error)); ok {
		return rf(ctx, user)
	}
	if rf, ok := ret.Get(0).(func(context.Context, helperstructs.UserReq) responce.UserData); ok {
		r0 = rf(ctx, user)
	} else {
		r0 = ret.Get(0).(responce.UserData)
	}

	if rf, ok := ret.Get(1).(func(context.Context, helperstructs.UserReq) error); ok {
		r1 = rf(ctx, user)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// NewUserUsecaseInterface creates a new instance of UserUsecaseInterface. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewUserUsecaseInterface(t interface {
	mock.TestingT
	Cleanup(func())
}) *UserUsecaseInterface {
	mock := &UserUsecaseInterface{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
